In [ ]:
# load dependencies
import pandas as pd
import os

In [2]:
# Load Stats Can crops .csv file ("3210035901_databaseLoadingData.csv")
canada_crops_df = pd.read_csv('Resources/3210035901_databaseLoadingData.csv')
canada_crops_df.head()

,REF_DATE,GEO,DGUID,Harvest disposition,Type of crop,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,1908,Canada,2021A000011124,Production (metric tonnes),Corn for grain,Metric tonnes,214,units,0,v114995731,1.19.11,580600.0,NaN,NaN,NaN,0
1,1909,Canada,2021A000011124,Production (metric tonnes),Corn for grain,Metric tonnes,214,units,0,v114995731,1.19.11,489600.0,NaN,NaN,NaN,0
2,1910,Canada,2021A000011124,Production (metric tonnes),Corn for grain,Metric tonnes,214,units,0,v114995731,1.19.11,363600.0,NaN,NaN,NaN,0
3,1911,Canada,2021A000011124,Production (metric tonnes),Corn for grain,Metric tonnes,214,units,0,v114995731,1.19.11,487400.0,NaN,NaN,NaN,0
4,1912,Canada,2021A000011124,Production (metric tonnes),Corn for grain,Metric tonnes,214,units,0,v114995731,1.19.11,430100.0,NaN,NaN,NaN,0

In [18]:
# Look at the shape of the df
canada_crops_df.shape

(236, 16)

In [17]:
# Look for Nan entries
canada_crops_df.isnull().sum()

REF_DATE                 0
GEO                      0
DGUID                    0
Harvest disposition      0
Type of crop             0
UOM                      0
UOM_ID                   0
SCALAR_FACTOR            0
SCALAR_ID                0
VECTOR                   0
COORDINATE               0
VALUE                    0
STATUS                 236
SYMBOL                 232
TERMINATED             236
DECIMALS                 0
dtype: int64

3 entire columns ("STATUS", "SYMBOL", "TERMINATED") are completely NaN.

In [3]:
# List columns
canada_crops_df.columns

Index(['REF_DATE', 'GEO', 'DGUID', 'Harvest disposition', 'Type of crop',
       'UOM', 'UOM_ID', 'SCALAR_FACTOR', 'SCALAR_ID', 'VECTOR', 'COORDINATE',
       'VALUE', 'STATUS', 'SYMBOL', 'TERMINATED', 'DECIMALS'],
      dtype='object')

In [7]:
# Check that it's all Canada stats (should be)
canada_crops_df['GEO'].unique()

array(['Canada'], dtype=object)

In [16]:
# Look at "DGUID" column
canada_crops_df['DGUID'].unique()

array(['2021A000011124'], dtype=object)

In [ ]:
# Look at 'Harvest disposition' column
canada_crops_df['Harvest disposition'].unique()

array(['Production (metric tonnes)'], dtype=object)

In [ ]:
# Look at 'Type of crop' column
canada_crops_df['Type of crop'].unique()

array(['Corn for grain', 'Lentils', 'Wheat, all', 'Wheat, durum',
       'Wheat, spring', 'Wheat, winter remaining'], dtype=object)

This project only requires "Corn for grain" and "Wheat, all".

In [12]:
# Drop all rows from 'Type of crop' except "Corn for grain" and "Wheat, all"
canada_crops_df = canada_crops_df[
    canada_crops_df['Type of crop'].isin(["Corn for grain", "Wheat, all"])
    ]
canada_crops_df["Type of crop"].unique()

array(['Corn for grain', 'Wheat, all'], dtype=object)

In [14]:
# Rename "Corn for grain" = "Corn" and "Wheat, all" = "Wheat"
canada_crops_df['Type of crop'] = canada_crops_df['Type of crop'].replace({
    "Corn for grain": "Corn",
    "Wheat, all": "Wheat"
})

canada_crops_df["Type of crop"].unique()

array(['Corn', 'Wheat'], dtype=object)

In [15]:
# Look at 'UOM' column
canada_crops_df["UOM"].unique()

array(['Metric tonnes'], dtype=object)

All data will be listed in Metric tonnes. This column could be eliminated and Metric tonnes can be listed in "Value" column.

In [19]:
canada_crops_df.head()

,REF_DATE,GEO,DGUID,Harvest disposition,Type of crop,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,1908,Canada,2021A000011124,Production (metric tonnes),Corn,Metric tonnes,214,units,0,v114995731,1.19.11,580600.0,NaN,NaN,NaN,0
1,1909,Canada,2021A000011124,Production (metric tonnes),Corn,Metric tonnes,214,units,0,v114995731,1.19.11,489600.0,NaN,NaN,NaN,0
2,1910,Canada,2021A000011124,Production (metric tonnes),Corn,Metric tonnes,214,units,0,v114995731,1.19.11,363600.0,NaN,NaN,NaN,0
3,1911,Canada,2021A000011124,Production (metric tonnes),Corn,Metric tonnes,214,units,0,v114995731,1.19.11,487400.0,NaN,NaN,NaN,0
4,1912,Canada,2021A000011124,Production (metric tonnes),Corn,Metric tonnes,214,units,0,v114995731,1.19.11,430100.0,NaN,NaN,NaN,0

In [23]:
# Drop columns
canada_crops_df = canada_crops_df[["REF_DATE", "GEO", "Type of crop", "VALUE"]]
canada_crops_df.head()

   REF_DATE     GEO Type of crop     VALUE
0      1908  Canada         Corn  580600.0
1      1909  Canada         Corn  489600.0
2      1910  Canada         Corn  363600.0
3      1911  Canada         Corn  487400.0
4      1912  Canada         Corn  430100.0